import 'dart:io';
import 'package:test/test.dart';

void main() {
  late Directory tempDir;

  setUp(() {
    tempDir = Directory.systemTemp.createTempSync('dtrx_integration_test');
  });

  tearDown(() {
    if (tempDir.existsSync()) {
      tempDir.deleteSync(recursive: true);
    }
  });

  group('CLI Integration Tests', () {
    test('Compiles a valid .dtrx file successfully', () async {
      final sourceFile = File('${tempDir.path}/button.dtrx');
      sourceFile.writeAsStringSync('''
component UserProfile(required String name, int age = 18) {
  return (
    <Center>
      <div style="width: 200px; height: 150px;">
        <Text value="Hello" />
        <Button icon={Icon(Icons.ac_unit)} onPressed={() => print("Hello")} />
      </div>
    </Center>
  );
}

component Clicker() {
  signal int count = 0;
  return (
    <Column>
      <Text value="Count: {count}" />
      <Button text="Add" onPressed={() => count++} />
    </Column>
  );
}
''');

      final result = await Process.run('dart', ['run', 'bin/dtrx.dart', sourceFile.path]);

      expect(result.exitCode, equals(0));

      final outFile = File('${tempDir.path}/button.dtrx.dart');
      expect(outFile.existsSync(), isTrue);

      final outputCode = outFile.readAsStringSync().trim();
      final expectedCode =
          '''
// GENERATED BY DTRX — DO NOT EDIT MANUALLY
// Source: ${sourceFile.path}

import 'package:flutter/material.dart';

class UserProfile extends StatelessWidget {
  final String name;
  final int age;

  const UserProfile({super.key, required this.name, this.age = 18});

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Container(
        width: 200.0,
        height: 150.0,
        child: Column(
          children: [
            Text("Hello"),
            IconButton(
              icon: Icon(Icons.ac_unit),
              onPressed: () => print("Hello"),
            ),
          ],
        ),
      ),
    );
  }
}

class Clicker extends StatefulWidget {
  const Clicker({super.key});

  @override
  State<Clicker> createState() => _ClickerState();
}

class _ClickerState extends State<Clicker> {
  int count = 0;

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Text("Count: \${count}"),
        ElevatedButton(
          onPressed: () => setState(() {
            count++;
          }),
          child: Text("Add"),
        ),
      ],
    );
  }
}
'''
              .trim();

      expect(outputCode.replaceAll('\r\n', '\n'), equals(expectedCode.replaceAll('\r\n', '\n')));
    });

    test('Reports error on undefined signal', () async {
      final sourceFile = File('${tempDir.path}/undefined_signal.dtrx');
      sourceFile.writeAsStringSync('''
component BadComponent() {
  return (
    <Button text="Click" onPressed={() => age++} />
  );
}
''');

      final result = await Process.run('dart', ['run', 'bin/dtrx.dart', sourceFile.path]);

      expect(result.exitCode, equals(1));
      expect(result.stdout.toString(), contains('[dtrx error]'));
      expect(result.stdout.toString(), contains("Undefined signal 'age'"));
    });

    test('Reports error on invalid layout primitive', () async {
      final sourceFile = File('${tempDir.path}/invalid_primitive.dtrx');
      sourceFile.writeAsStringSync('''
component BadLayout() {
  return (
    <paragraph>
      <Text value="Hello" />
    </paragraph>
  );
}
''');

      final result = await Process.run('dart', ['run', 'bin/dtrx.dart', sourceFile.path]);

      expect(result.exitCode, equals(1));
      expect(result.stdout.toString(), contains('[dtrx error]'));
      expect(result.stdout.toString(), contains("Invalid tag: 'paragraph'"));
    });
  });
}
