import 'ast.dart';
import 'errors.dart';
import 'css_parser.dart';
import 'virtual_tags.dart';

class CodeGen {
  final String file;
  final List<DTRXError> warnings = [];

  CodeGen({required this.file});

  String generate(ProgramNode program) {
    final buffer = StringBuffer();

    buffer.writeln('// GENERATED BY DTRX — DO NOT EDIT MANUALLY');
    buffer.writeln('// Source: $file');
    buffer.writeln();
    buffer.writeln("import 'package:flutter/material.dart';");
    buffer.writeln();

    for (var node in program.body) {
      if (node is ComponentNode) {
        buffer.write(_generateComponent(node));
      } else if (node is DartStatementNode) {
        buffer.writeln(node.rawCode);
        buffer.writeln();
      }
    }
    return '${buffer.toString().trim()}\n';
  }

  String _generateComponent(ComponentNode component) {
    final buffer = StringBuffer();

    final signals = <SignalDeclNode>[];
    for (var node in component.body) {
      if (node is SignalDeclNode) {
        signals.add(node);
      }
    }

    final signalNames = signals.map((s) => s.name).toList();

    if (signals.isEmpty) {
      // StatelessWidget
      buffer.writeln('class ${component.name} extends StatelessWidget {');
      for (var param in component.params) {
        buffer.writeln('  final ${param.type} ${param.name};');
      }
      if (component.params.isNotEmpty) buffer.writeln();

      buffer.write('  const ${component.name}({super.key');
      for (var param in component.params) {
        buffer.write(', ');
        if (param.required) {
          buffer.write('required this.${param.name}');
        } else {
          buffer.write('this.${param.name}');
          if (param.defaultValue != null) {
            buffer.write(' = ${param.defaultValue}');
          }
        }
      }
      buffer.writeln('});');
      buffer.writeln();
      buffer.writeln('  @override');
      buffer.writeln('  Widget build(BuildContext context) {');

      for (var node in component.body) {
        if (node is VarNode) {
          buffer.writeln(
            '    final ${node.name} = ${_generateMarkup(node.markup, signalNames, 4)};',
          );
        } else if (node is DartStatementNode) {
          buffer.writeln('    ${node.rawCode};');
        }
      }
      final returnNode = component.body.firstWhere((n) => n is ReturnNode) as ReturnNode;
      buffer.writeln('    return ${_generateMarkup(returnNode.markup, signalNames, 4)};');
      buffer.writeln('  }');
      buffer.writeln('}');
      buffer.writeln();
    } else {
      // StatefulWidget
      buffer.writeln('class ${component.name} extends StatefulWidget {');
      for (var param in component.params) {
        buffer.writeln('  final ${param.type} ${param.name};');
      }
      if (component.params.isNotEmpty) buffer.writeln();

      buffer.write('  const ${component.name}({super.key');
      for (var param in component.params) {
        buffer.write(', ');
        if (param.required) {
          buffer.write('required this.${param.name}');
        } else {
          buffer.write('this.${param.name}');
          if (param.defaultValue != null) {
            buffer.write(' = ${param.defaultValue}');
          }
        }
      }
      buffer.writeln('});');
      buffer.writeln();
      buffer.writeln('  @override');
      buffer.writeln('  State<${component.name}> createState() => _${component.name}State();');
      buffer.writeln('}');
      buffer.writeln();

      // State class
      buffer.writeln('class _${component.name}State extends State<${component.name}> {');
      for (var sig in signals) {
        buffer.writeln('  ${sig.type} ${sig.name} = ${sig.initializer};');
      }
      if (signals.isNotEmpty) buffer.writeln();

      buffer.writeln('  @override');
      buffer.writeln('  Widget build(BuildContext context) {');

      for (var node in component.body) {
        if (node is VarNode) {
          buffer.writeln(
            '    final ${node.name} = ${_generateMarkup(node.markup, signalNames, 4)};',
          );
        } else if (node is DartStatementNode) {
          buffer.writeln('    ${node.rawCode};');
        }
      }
      final returnNode = component.body.firstWhere((n) => n is ReturnNode) as ReturnNode;
      buffer.writeln('    return ${_generateMarkup(returnNode.markup, signalNames, 4)};');
      buffer.writeln('  }');
      buffer.writeln('}');
      buffer.writeln();
    }

    return buffer.toString();
  }

  String _generateMarkup(MarkupNode node, List<String> signalNames, int indent) {
    if (node is SelfClosingTagNode) {
      return _generateTag(
        node.tagName,
        node.attributes,
        [],
        signalNames,
        node.line,
        node.column,
        indent,
      );
    } else if (node is ParentTagNode) {
      return _generateTag(
        node.tagName,
        node.attributes,
        node.children,
        signalNames,
        node.line,
        node.column,
        indent,
      );
    }
    return '';
  }

  AttributeNode? _findAttribute(List<AttributeNode> attributes, String key) {
    for (final a in attributes) {
      if (a.key == key) return a;
    }
    return null;
  }

  String _generateTag(
    String tagName,
    List<AttributeNode> attributes,
    List<MarkupChild> children,
    List<String> signalNames,
    int line,
    int column,
    int indent,
  ) {
    final nextIndent = indent + 2;

    if (virtualTagNames.contains(tagName)) {
      final resolved = resolveVirtualTag(
        tagName,
        attributes,
        warnings: warnings,
        file: file,
        line: line,
        column: column,
      );
      if (resolved != null) {
        List<MarkupChild> resolvedChildren = children;
        if (resolved.syntheticChild != null) {
          resolvedChildren = [MarkupNodeChild(resolved.syntheticChild!)];
        }
        return _generateTag(
          resolved.flutterWidgetName,
          resolved.remappedAttributes,
          resolvedChildren,
          signalNames,
          line,
          column,
          indent,
        );
      }
    }

    if (tagName == 'div' || tagName == 'span') {
      final styleAttr = _findAttribute(attributes, 'style');
      CssProperties? cssProps;
      if (styleAttr != null && styleAttr.value is LiteralAttributeValue) {
        final styleLiteral = (styleAttr.value as LiteralAttributeValue).value as String;
        cssProps = CssParser.parse(
          styleLiteral,
          file: file,
          line: styleAttr.line,
          column: styleAttr.column,
          warnings: warnings,
        );
      }

      final params = <String>[];
      if (cssProps != null) {
        if (cssProps.width != null) {
          params.add('width: ${cssProps.width}');
        }
        if (cssProps.height != null) {
          params.add('height: ${cssProps.height}');
        }
        if (cssProps.padding != null) {
          params.add('padding: ${cssProps.padding!.toFlutterCode()}');
        }
        if (cssProps.margin != null) {
          params.add('margin: ${cssProps.margin!.toFlutterCode()}');
        }

        final hasBg = cssProps.backgroundColor != null;
        final hasRadius = cssProps.borderRadius != null;
        final hasShadow = cssProps.boxShadow != null;
        if (hasBg || hasRadius || hasShadow) {
          final decorationParams = <String>[];
          if (hasBg) {
            decorationParams.add('color: ${cssProps.backgroundColor!.toFlutterCode()}');
          }
          if (hasRadius) {
            decorationParams.add('borderRadius: ${cssProps.borderRadius!.toFlutterCode()}');
          }
          if (hasShadow) {
            decorationParams.add('boxShadow: [${cssProps.boxShadow!.toFlutterCode()}]');
          }
          params.add('decoration: BoxDecoration(${decorationParams.join(", ")})');
        }
      }

      if (children.isNotEmpty) {
        if (children.length == 1) {
          params.add('child: ${_generateChildCode(children[0], signalNames, nextIndent)}');
        } else {
          final innerWidget = tagName == 'div' ? 'Column' : 'Row';
          final innerCode = _generateTag(
            innerWidget,
            [],
            children,
            signalNames,
            line,
            column,
            nextIndent,
          );
          params.add('child: $innerCode');
        }
      }

      // Format Container
      if (params.isEmpty) {
        return 'Container()';
      } else {
        final sb = StringBuffer();
        sb.writeln('Container(');
        for (var p in params) {
          sb.writeln('${_indentStr(nextIndent)}$p,');
        }
        sb.write('${_indentStr(indent)})');
        return sb.toString();
      }
    }

    // Native Flutter Widgets
    const singleChildWidgets = {
      'Center',
      'Padding',
      'SizedBox',
      'Align',
      'Expanded',
      'Flexible',
      'ClipRRect',
      'GestureDetector',
      'InkWell',
      'DecoratedBox',
      'Container',
      'ElevatedButton',
      'SingleChildScrollView',
    };
    final isSingleChild = singleChildWidgets.contains(tagName);

    if (tagName == 'Text') {
      final valueAttr = _findAttribute(attributes, 'value');
      final otherAttrs = attributes.where((a) => a.key != 'value');

      String textPosValue = '""';
      if (valueAttr != null) {
        textPosValue = _generateAttributeValueCode(valueAttr.value, signalNames, nextIndent);
      }

      final otherParams = otherAttrs
          .map(
            (a) =>
                '${a.key}: ${_generateAttributeValueCode(a.value, signalNames, nextIndent, isCallback: a.key.startsWith("on"))}',
          )
          .toList();
      return 'Text($textPosValue${otherParams.isNotEmpty ? ", ${otherParams.join(", ")}" : ""})';
    }

    if (tagName == 'Image.asset' || tagName == 'Image.network') {
      final posKey = tagName == 'Image.asset' ? 'src' : 'url';
      final posAttr = _findAttribute(attributes, posKey);
      final otherAttrs = attributes.where((a) => a.key != posKey);

      String posValue = '""';
      if (posAttr != null) {
        posValue = _generateAttributeValueCode(posAttr.value, signalNames, nextIndent);
      }

      final otherParams = otherAttrs
          .map(
            (a) =>
                '${a.key}: ${_generateAttributeValueCode(a.value, signalNames, nextIndent, isCallback: a.key.startsWith("on"))}',
          )
          .toList();
      return '$tagName($posValue${otherParams.isNotEmpty ? ", ${otherParams.join(", ")}" : ""})';
    }

    final params = attributes
        .map(
          (a) =>
              '${a.key}: ${_generateAttributeValueCode(a.value, signalNames, nextIndent, isCallback: a.key.startsWith("on"))}',
        )
        .toList();
    if (children.isNotEmpty) {
      if (isSingleChild) {
        if (children.length == 1) {
          params.add('child: ${_generateChildCode(children[0], signalNames, nextIndent)}');
        } else {
          final columnCode = _generateTag(
            'Column',
            [],
            children,
            signalNames,
            line,
            column,
            nextIndent,
          );
          params.add('child: $columnCode');
        }
      } else {
        final childLines = _generateChildrenListCode(children, signalNames, nextIndent + 2);
        params.add('children: [\n$childLines\n${_indentStr(nextIndent)}]');
      }
    }

    if (params.isEmpty) {
      return '$tagName()';
    } else if (params.length == 1 && !params[0].contains('\n')) {
      return '$tagName(${params[0]})';
    } else {
      final sb = StringBuffer();
      sb.writeln('$tagName(');
      for (var p in params) {
        sb.writeln('${_indentStr(nextIndent)}$p,');
      }
      sb.write('${_indentStr(indent)})');
      return sb.toString();
    }
  }

  String _generateAttributeValueCode(
    AttributeValue val,
    List<String> signalNames,
    int indent, {
    bool isCallback = false,
  }) {
    if (val is LiteralAttributeValue) {
      if (val.value is String) {
        return _resolveStringInterpolation(val.value as String);
      }
      return val.value.toString();
    }
    if (val is ExpressionAttributeValue) {
      if (isCallback) {
        return _wrapMutationsInSetState(val.dartExpr, signalNames, indent);
      }
      return val.dartExpr;
    }
    return '';
  }

  String _indentStr(int indent) => ' ' * indent;

  String _generateChildCode(MarkupChild child, List<String> signalNames, int indent) {
    if (child is MarkupNodeChild) {
      return _generateMarkup(child.node, signalNames, indent);
    }
    if (child is TextNodeChild) {
      final interpolated = _resolveStringInterpolation(child.text);
      return 'Text("""$interpolated""")';
    }
    if (child is ExpressionChild) {
      return child.dartExpr;
    }
    if (child is ConditionalChild) {
      if (child.children.length == 1) {
        return '${child.condition} ? ${_generateChildCode(child.children[0], signalNames, indent)} : const SizedBox.shrink()';
      } else {
        final childLines = _generateChildrenListCode(child.children, signalNames, indent + 2);
        return '${child.condition} ? Column(children: [\n$childLines\n${_indentStr(indent)}]) : const SizedBox.shrink()';
      }
    }
    return '';
  }

  String _generateChildrenListCode(
    List<MarkupChild> children,
    List<String> signalNames,
    int indent,
  ) {
    final childCodes = <String>[];
    for (var child in children) {
      if (child is MarkupNodeChild) {
        childCodes.add('${_indentStr(indent)}${_generateMarkup(child.node, signalNames, indent)},');
      } else if (child is TextNodeChild) {
        final interpolated = _resolveStringInterpolation(child.text);
        childCodes.add('${_indentStr(indent)}Text("""$interpolated"""),');
      } else if (child is ExpressionChild) {
        childCodes.add('${_indentStr(indent)}${child.dartExpr},');
      } else if (child is ConditionalChild) {
        final childLines = _generateChildrenListCode(child.children, signalNames, indent + 2);
        childCodes.add(
          '${_indentStr(indent)}if (${child.condition}) ...[\n$childLines\n${_indentStr(indent)}],',
        );
      }
    }
    return childCodes.join('\n');
  }

  String _resolveStringInterpolation(String str) {
    return str.replaceAllMapped(RegExp(r'\{([^}]+)\}'), (m) => '\${${m.group(1)}}');
  }

  String _wrapMutationsInSetState(String expr, List<String> signals, int indent) {
    var result = expr;
    final indentStr = ' ' * indent;
    final bodyIndentStr = ' ' * (indent + 2);
    for (var s in signals) {
      final postfixRegex = RegExp(r'\b(' + RegExp.escape(s) + r'\s*(\+\+|--))');
      result = result.replaceAllMapped(
        postfixRegex,
        (m) => 'setState(() {\n$bodyIndentStr${m.group(1)};\n$indentStr})',
      );

      final prefixRegex = RegExp(r'\b((\+\+|--)\s*' + RegExp.escape(s) + r')');
      result = result.replaceAllMapped(
        prefixRegex,
        (m) => 'setState(() {\n$bodyIndentStr${m.group(1)};\n$indentStr})',
      );

      final assignRegex = RegExp(
        r'\b(' + RegExp.escape(s) + r'\s*(=|\+=|-=|\*=|\/=|%=)\s*([^;,\n]+))',
      );
      result = result.replaceAllMapped(
        assignRegex,
        (m) => 'setState(() {\n$bodyIndentStr${m.group(1)};\n$indentStr})',
      );
    }
    return result;
  }
}
